version: '2'
services:
    seguridmap-app:
        image: seguridmap
        external_links:
            - seguridmap-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/seguridMap
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    seguridmap-postgresql:
        extends:
            file: postgresql.yml
            service: seguridmap-postgresql
